version: 1
output:
  dir: website/src/docs/reference/properties
  index: index.md
features:
  generateIndex: true
  linkAutoDetection: true
schema:
  storeEnv: JSON_SCHEMA_STORE_LOCAL
  url: https://taskfile.dev/schema.json
watch:
  debounceMs: 400
markdown:
  format: md
  remarkLint: false
data:
  propertiesDir: website/config/task-docs-gen/data/properties
templates:
  dir: website/config/task-docs-gen/templates
